services:
  - type: web
    name: fishversa-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@fishversa.com
      - key: ADMIN_PASSWORD
        value: AdminPassword123!
